### ISSUE TITLE
Publish to Hex?

### ISSUE THREAD

**Issue by cdegroot** [armon/erl-rstar#4]
@armon would you be amenable to a PR that upgrades to rebar3 and publishes this to Hex? I'd like to use the project from an Elixir one and this seems to be the quick/simple/lazy approach. 

(alternatively, I can fork and publish with my GH handle prefixed, so no harm done if you don't want such a PR ;-))

**Comment by cdegroot** [comment]
(https://github.com/armon/erl-rstar/pull/5 should do the trick but I'm not an Erlang developer and cannot of course test the final publish-to-hex step under your name)

**Comment by armon** [comment]
@cdegroot Merged! Hope that works for you!

**Comment by cdegroot** [comment]
Well, technically you should also now actually publish it on Hex.pm ;). 

(don't sweat it though - it turned out that my dataset was too small to benefit much from indexing so I put using your library on the backburner - it worked great, but for 50 2D points it wasn't able to beat ETS and some matchers; which I don't hold against your code, it's just a fact of life that indexing only makes sense from a certain point).
